name: habit_flow
description: "HabitFlow — a production-ready habit tracking app built with Flutter."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  uuid: ^4.4.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/

flutter_intl:
  enabled: true
